### ISSUE TITLE
Panic: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by faelau** [Jozott00/drone-gitea-message#2]
Hello,

im getting a runtime error:

```
time="2024-07-10T12:25:47Z" level=info msg="Sending message as PR comment..."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x76b1c2]

goroutine 1 [running]:
code.gitea.io/sdk/gitea.(*Client).doRequest(0x0, {0x81875d, 0x4}, {0xc000428100, 0x38}, 0xc000125470, {0x8c3300?, 0xc000004330?})
	/go/pkg/mod/code.gitea.io/sdk/gitea@v0.17.1/client.go:330 +0x62
code.gitea.io/sdk/gitea.(*Client).getResponse(0xc000004330?, {0x81875d?, 0x0?}, {0xc000428100?, 0xc000248eb0?}, 0x411e85?, {0x8c3300?, 0xc000004330?})
	/go/pkg/mod/code.gitea.io/sdk/gitea@v0.17.1/client.go:441 +0x6c
code.gitea.io/sdk/gitea.(*Client).getParsedResponse(0xc000248f40?, {0x81875d?, 0x3?}, {0xc000428100?, 0xc000248f78?}, 0x411adb?, {0x8c3300?, 0xc000004330?}, {0x78eba0, 0xc00009a000})
	/go/pkg/mod/code.gitea.io/sdk/gitea@v0.17.1/client.go:463 +0x30
code.gitea.io/sdk/gitea.(*Client).CreateIssueComment(0x0, {0xc000020011, 0x9}, {0xc00001e310, 0x15}, 0x1, {{0xc00044a020, 0x10}})
	/go/pkg/mod/code.gitea.io/sdk/gitea@v0.17.1/issue_comment.go:113 +0x2be
main.(*messageClient).sendMessage(0xb454a0?)
	/app/message.go:30 +0xb8
main.Plugin.Exec({{{0xc000020011, 0x9}, {0xc00001e310, 0x15}}, {0x1}, {{0xc0000202b2, 0xc}}, {{0xc0000241cf, 0x28}, {0xc00001e374, ...}, ...}})
	/app/plugin.go:111 +0x825
main.run(0xc0001fe2c0)
	/app/main.go:113 +0x3e5
github.com/urfave/cli.HandleAction({0x79f760?, 0x857910?}, 0xc000102540?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x50
github.com/urfave/cli.(*App).Run(0xc000102540, {0xc000116140, 0x1, 0x1})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:286 +0x79b
main.main()
	/app/main.go:82 +0x965
```

I tested the plugin on various runners with the same result. Plugin version is `v0.2.1`.

**Comment by Jozott00** [comment]
It seems that the segfault is caused in the [gitea go-sdk](https://gitea.com/gitea/go-sdk). Please double check your configurations,  especially the `base_url`. Also is it triggered by a PR event?
